apiVersion: apps/v1
kind: Deployment
metadata:
    name: authserver
    labels:
       app: authserver
spec:
  replicas: 1
  selector:
        matchLabels:
            app: authserver
  template:
        metadata:
          labels:
            app: authserver
        spec:
          containers:
           - name: authserver
             image: abhisheknn/authserver:latest
             imagePullPolicy: Never	
             ports:
             - containerPort: 8252
           - name: redis
             image: redis
             ports:
             - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
    name: authserversvc
spec:
    ports:
    - name: "authserverport"
      port: 8252
      targetPort: 8252
      nodePort: 32655   
    selector:
      app: authserver
    type: NodePort  
